### ISSUE TITLE
Agent<->Endpoint connection can reset, causing Endpoint CPU spikes on Windows

### ISSUE THREAD

**Issue by ferullo** [elastic/endpoint#21]
Some users are having an issue with the connection between Agent and Endpoint resetting periodically (about every 30 to 60 minutes). When that connection resets, Endpoint reapplies its policy/configuration from Agent which can spike CPU for about 30 to 60 seconds on Windows.

To prevent these needless reapplications of Endpoint's policy, Endpoint should simply not reapply a policy that is identical to the one it is already using.

**Comment by ph** [comment]
@ferullo Do we know why the reset happen, is there heavy load on the machine?

**Comment by ferullo** [comment]
This issue isn't new but we've seen recent cases where the CPU spike appears to be more regular and impactful than in the past, which is driving this workaround.

**Comment by ferullo** [comment]
This was addressed in 8.3.0 and 7.17.5, if this problem isn't resolved we'll re-open it.
