### ISSUE TITLE
elasticendpoint can't communicate with API

### ISSUE THREAD

**Issue by halimB8** [elastic/endpoint#3]
Hello, 

I am trying to use elastic endpoint security, and when I start it, I am getting this errors: 

```
'ERROR': sub_type: 'FAILED' message: Application: endpoint-security--7.9.2[: State changed to FAILED: Missed two check-ins
Could not communicate with Checking API will retry, error: fail to checkin to fleet: Post "https://X.X.X.X:5601/api/ingest_manager/fleet/agents/XXXXXXXXX/checkin?": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
I am using (elastic, kibana, endpoint) version 7.9.2
install endpoint on linux and windows and I got the same error
to run the endpoint on linuxI am using the command  :

```
sudo elastic-agent enroll  https://X.X.X.X:5601 @enrollment_key
```

**Comment by gabriellandau** [comment]
Hi @halimB8.  This discussion might be related: https://discuss.elastic.co/t/elastic-endpoint-could-not-communicate-with-checking-api-will-retry/251303/2

**Comment by halimB8** [comment]
Hi @gabriellandau 
Yes it was the case for me, now the endpoint is working perfectly 
thanks for your help
