### ISSUE TITLE
Elastic Endpoint hits "perf" buffer limit on EXECVE monitoring via kprobe when executable command arguments larger than 2048 bytes

### ISSUE THREAD

**Issue by gpapakyriakopoulos** [elastic/endpoint#4]
As the title suggests, Elastic Endpoint leverages "perf" to attach and consume kprobe trace events to monitor EXECVE calls on the kernel. 

The "perf" module has a built-in hard event buffer limit of 2048 bytes as shown in the relevant C code :

```
include/linux/trace_events.h:
#define PERF_MAX_TRACE_SIZE 2048
```
https://github.com/torvalds/linux/blob/master/include/linux/trace_events.h#L633
https://github.com/torvalds/linux/blob/master/kernel/trace/trace_event_perf.c#L402

When an executed process contains arguments with total size larger than 2048 bytes and the relevant kprobe trace attempts to parse the event, the trace buffer is overflown which results in a kernel warning being issued and the kernel taint flag being set as visible on the error below :

```
[ 3634.568530] ------------[ cut here ]------------
[ 3634.568532] perf buffer not large enough
[ 3634.568568] WARNING: CPU: 0 PID: 9820 at kernel/trace/trace_event_perf.c:397 perf_trace_buf_alloc+0x7f/0x90
[ 3634.568569] Modules linked in: crct10dif_pclmul nft_counter crc32_pclmul binfmt_misc xt_multiport bochs_drm ghash_clmulni_intel ttm xt_pkttype xt_tcpudp xt_state drm_kms_helper xt_conntrack nft_compat drm evdev joydev serio_raw sg virtio_balloon pcspkr qemu_fw_cfg button nf_tables nfnetlink nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c ip_tables x_tables autofs4 ext4 crc16 mbcache jbd2 crc32c_generic fscrypto ecb hid_generic usbhid hid sr_mod cdrom ata_generic virtio_net net_failover virtio_blk failover crc32c_intel aesni_intel uhci_hcd ehci_hcd ata_piix aes_x86_64 psmouse libata crypto_simd cryptd glue_helper usbcore scsi_mod i2c_piix4 virtio_pci virtio_ring virtio usb_common
[ 3634.568610] CPU: 0 PID: 9820 Comm: check_mk_agent Not tainted 4.19.0-12-amd64 #1 Debian 4.19.152-1
[ 3634.568611] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.10.2-1 04/01/2014
[ 3634.568613] RIP: 0010:perf_trace_buf_alloc+0x7f/0x90
[ 3634.568614] Code: 48 c7 44 18 f8 00 00 00 00 5b 5d 41 5c c3 80 3d 3a 76 f8 00 00 75 15 48 c7 c7 6b 75 46 9a c6 05 2a 76 f8 00 01 e8 8b 9c f0 ff <0f> 0b 5b 31 c0 5d 41 5c c3 0f 1f 84 00 00 00 00 00 55 89 f5 53 48
[ 3634.568615] RSP: 0018:ffff9c77c7ecfd78 EFLAGS: 00010286
[ 3634.568617] RAX: 0000000000000000 RBX: 000000000000109c RCX: 0000000000000000
[ 3634.568617] RDX: 0000000000000004 RSI: ffffffff9abf9afc RDI: 0000000000000246
```

This obviously is a serious issue, as setting the kernel taint flag potentially means that the kernel is no longer trusted.

You can easily reproduce the scenario on demand by having a system running elastic-agent and the endpoint services with default configuration. 

* Navigate to `/sys/kernel/debug/tracing/events/kprobes/elasticendpoint_SYS_EXECVEAT_ARGS_probe`
* Enable the kprobe event tracing by flipping the `enable` file to `1`
* Run a `/bin/echo` command with enough "a" characters as an argument to exceed the 2048 byte limit
* Check `dmesg` and observe the warning triggered
* Check kernel taint flag that should now contain the value `512` (denoting a kernel taint warning)

**Comment by ferullo** [comment]
Sorry it's been a few days without a response @gpapakyriakopoulos . This issue hasn't gone unnoticed and we'll respond more thoroughly in another week or so.

**Comment by gpapakyriakopoulos** [comment]
Hey @ferullo 
Thanks for letting me know, any updates on this ?

**Comment by ferullo** [comment]
Hi @gpapakyriakopoulos we're still looking into whether or not we can find a way to gather process arguments without tripping this warning in the kernel.

**Comment by ferullo** [comment]
Hi @gpapakyriakopoulos we were able to find a solution to this issue. The fix will be in 7.12.1 so I'm closing this. After 7.12.1 is released if you continue to see this issue please re-open. Thanks for reporting and bearing with us as we worked through the issue.

**Comment by gpapakyriakopoulos** [comment]
@ferullo Thanks for the very quick turnaround, we are seriously impressed! Just wanted to ask any idea when we could expect the 7.12.1 version to be available for download ? No pressure just so we can plan our infrastructure upgrade in the meantime.

**Comment by ferullo** [comment]
I don't have an exact release date for it. I imagine it'll be a few weeks.
