### ISSUE TITLE
multiple errors with 7.12 on mac laptop

### ISSUE THREAD

**Issue by LANopop** [elastic/endpoint#5]
i am seeing the following errors for the latest elastic-agent (7.12) on mac

`[elastic_agent.endpoint_security][error] Events_Watcher.cpp:950 Intercepted unsupported file event type [6]
[elastic_agent.endpoint_security][error] MessageCallbackManager.cpp:420 process id 75234: [/Applications/Adobe Acrobat Reader DC.app/Contents/Frameworks/RdrCEF Helper.app/Contents/MacOS/RdrCEF Helper] is [allowed] due to message processing failure, error code -4
[elastic_agent.endpoint_security][error] Interfaces.cpp:121 Interface name too long to get MAC address; name [bridge0], namelen [7], sizeof(sdl_data) [12] (see net/if_dl.h -> sdl_data)
[elastic_agent.endpoint_security][error] MessageCallbackManager.cpp:420 process id 78398: [/Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/89.0.4389.90/Helpers/Google Chrome Helper (Renderer).app/Contents/MacOS/Google Chrome Helper (Renderer)] is [allowed] due to message processing failure, error code -4`

**Comment by willyu-elastic** [comment]
Hello, can you provide some details as to what version of macOS this is? Thanks!

**Comment by LANopop** [comment]
big sur 11.2.3

**Comment by willyu-elastic** [comment]
Thank you for the info, can you also retrieve the output of `sudo systemextensionsctl list`. A few other questions

1) Was this installed via JAMF?
2) If not JAMF, did you click "Allow" for the system extension to load, and subsequently did you also click "Allow" when the network filtering prompt popped up? 

thanks!

**Comment by LANopop** [comment]
systemextensionsctl list
1 extension(s)
--- com.apple.system_extension.endpoint_security
enabled	active	teamID	bundleID (version)	name	[state]
*	*	xxxxxxx	co.elastic.systemextension (7.12.0/7.12.9000466co.elastic.systemextension	[activated enabled]

not installed via JAMF
we gave all the permissions to the elastic agent (this was not done right after the installation but after a couple of days, because it was not clear to the user at the time what to do)

**Comment by willyu-elastic** [comment]
Thank you @LANopop, can you also describe what was being done at the time of seeing these log errors? I see there was something regarding Adobe Reader DC. Was this opening a PDF when Adobe Reader DC was not already running? Have you seen any other errors in the logs since then? Thanks!

**Comment by LANopop** [comment]
have no details on that. happened during testing the elastic cloud trial and i have no access to it anymore.

**Comment by ferullo** [comment]
The interface name issue was fixed. The system extension issue was never diagnosed but this issue has gone stale.
