### ISSUE TITLE
Endpoint Firewall in MacOs

### ISSUE THREAD

**Issue by CyberTaoFlow** [elastic/endpoint#52]
Hello,

**Problem Description**

When the endpoint agent is active the MacOS firewall understandably becomes enabled presumably to provide isolation function and certainly to increase the protection level of the host from network based attacks.   

Our issue is that we are unable to influence this feature from a  policy perspective.  For example some users have the need to launch applications on the fly that need to accept incoming connections.  

**Workaround :/**
Currently when the development team do hackathon's  they stop the endpoint agent in order to avoid being nagged every time they fire up a newly compiled iteration of the subject application on a different port.    

We have tried adding a trusted application using a custom path which has stopped the endpoint from blocking execution (rare but was happening) but this has not prevented the macos firewall from prompting regarding the firewall.

We have advised the team to consider signing their builds which should allow trusting the signer in the MacOS firewall but would also like a means to control this feature to any degree on the endpoint.    

**Feature Request**
Either being able to provide something like host isolation exception mentioned here (https://github.com/elastic/endpoint/issues/28) but to be used during non isolated operation and including local listening port  and remote network filter would be great or at the very least a means of disabling the inbound block on a policy by policy basis would be great.

**Comment by ferullo** [comment]
Hi, sorry this issue has gone so long without a response.

What you're describing doesn't sound like anything Elastic Endpoint does. Unless you've enabled host isolation Endpoint doesn't apply a firewall to the system. Is it possible you've enabled host isolation? if not, maybe this is caused by an interaction between Endpoint and some other application in your computer.

**Comment by CyberTaoFlow** [comment]
An example of unexpected interaction with MacOs network extension handling with confimation from an elastician can be found here:

https://discuss.elastic.co/t/external-nic-blocked-by-elastic-agent/290772/22

Notably the users in question in our case were on new Apple silicon and only experienced this issue after bringing up a VPN that did not use split-tunneling.

Today they are no longer seeing the issue so ill close this but still think the feature request is worth consideration.
Thanks!
