### ISSUE TITLE
SSH log events recognize wrong source IP

### ISSUE THREAD

**Issue by maof97** [elastic/endpoint#6]
Hello guys,

I made a rule-tuning issue in the detection-rules git already [here](https://github.com/elastic/detection-rules/issues/1074).

> For me, on Ubuntu 20.04.2 LTS (Focal Fossa) this rule [SSH (Secure Shell) from the Internet] triggers exactly every time I log in via SSH locally and then type sudo -s and my password.
> The source IP of the alerted event is always a random public Ip X.X.0.0 where X are sometimes the same, but not consistently. The 0.0. is always the same (which makes an attack very unlikely). Also I don't have any respective ports open to even allow SSH from the internet, so this must be a false positive.

I was told that I need to open a **bug** issue here, as the rule worked as intended but the alert shouldn't trigger anyway.
The problem was already ruled out to not be a problem on my site and that maybe another person has the same problem already (see linked issue).

It would be great if this issue could get fixed.

Greetings
Martin

**Comment by peasead** [comment]
@maof97 

Just a quick update, I've created an internal ticket for our endpoint team. 

Thanks for your patience and for reporting this.

**Comment by nicholasberlin** [comment]
I was able to reproduce this locally. Working on it.

**Comment by nicholasberlin** [comment]
The fix will be included in the 7.13 release.

**Comment by maof97** [comment]
@nicholasberlin 

> The fix will be included in the 7.13 release.

That’s very nice! I wonder where the bug came from?

**Comment by nfritts** [comment]
Hi @maof97,

Sorry that this lingered so long.  The issue was a change in the behavior of inet_getname with newer builds of the ubuntu kernel.  Thanks again for bringing it to our attention.
