### ISSUE TITLE
Field file.Ext.original.name missing in endpoint logs from Ubuntu servers

### ISSUE THREAD

**Issue by ar3diu** [elastic/endpoint#63]
I've noticed that `file.Ext.original.name` is not set in the logs collected with Elastic Defend from Ubuntu servers. 
Only `file.Ext.original.path` is parsed and appears in events.

**Comment by nfritts** [comment]
This should be an easy update.  I'm going to see if we can get this in to an upcoming release.  My best guess is that it will happen in 8.13.
