### ISSUE TITLE
Missing 8.12.0 images

### ISSUE THREAD

**Issue by Aqualie** [elastic/endpoint#64]
I don't see any 8.12.0 docker images:
https://www.docker.elastic.co/r/elastic-security/elastic-sec-attendant
https://www.docker.elastic.co/r/elastic-security/elastic-sec-endpoint

only elastic-agent 8.12.0 is available

**Comment by nick-alayil** [comment]
Hi @Aqualie, we no longer provide docker images for elastic-sec-attendant and elastic-sec-endpoint as we've stopped support for running Defend/Endpoint as a container in the agent daemonset within k8s. This decision was driven by the complexity of manifest changes required for Defend/Endpoint deployment in k8s and a shift towards prioritizing the [Defend for Containers](https://docs.elastic.co/integrations/cloud_defend) integration. Documentation link [here](https://www.elastic.co/guide/en/security/current/d4c-overview.html)

For those seeking to instrument security telemetry from k8s, we recommend transitioning to the Defend for Containers integration. However, if your use case revolves around traditional EDR capabilities such as malware protection and memory protection, we advise installing the Defend/Endpoint integration directly on k8s nodes.

**Comment by Aqualie** [comment]
Thanks I wasn't aware of this new integration I'll migrate over.
