### ISSUE TITLE
Unknown Host.id `00000000-0000-0000-0000-000000000000` for Endpoint (and same for Agent.id)

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/endpoint#7]
**Description:**
Unknown Host id `00000000-0000-0000-0000-000000000000` for host.id and for agent.id on data in Discover tab.
 - seeing this for all 3 OS variants installed (Ubuntu, Win 10, and Darwin)

**Kibana version:**  7.16.0 BC-5 Kibana Cloud-Staging environment

**Host OS and Browser version:**  All, All

**Build details:**
```
Build: 46061
Commit: f13296db8798dd0cd39ab6cc4a61a35a2a2b05cc
```

**Preconditions:**
1. 7.16.0 BC-5 Kibana Cloud-staging environment should be available.
2. Windows, Linux and MAC agents must be installed Default Policy with System and Endpoint Security.

**Steps to reproduce:**
1. Navigate to Discover tab.
2. Set `host.id:` filter and observe Unknown Host id `00000000-0000-0000-0000-000000000000`

**Query:**
Could anyone please share any update on this unknown host id available whose data is available under Discover tab.

**Screenshot:**
![4](https://user-images.githubusercontent.com/77374876/142386618-bcdfe409-49f8-4ed1-b5c1-5de2550ba177.JPG)

**Comment by ferullo** [comment]
This will be fixed in 7.16.1
