### ISSUE TITLE
[Defend] agent.name still missing

### ISSUE THREAD

**Issue by nicpenning** [elastic/endpoint#75]
I wanted to check in and see if this is by design.

Most log shippers within the stack (beats/elastic agent) shippers with agent.name. Elastic Defend telemetry events for example, process events, do not contain agent.name but other agent.* fields. Is this expected?

**Comment by intxgo** [comment]
Only one Elastic Endpoint (the endpoint service behind Elastic Defend) can be installed on the target host.

Anyway, it seems agent.name cannot be user defined yet, there's an open ticket, so in practice it's always equivalent to `host.hostname`
* https://github.com/elastic/elastic-agent/issues/86

**Comment by nicpenning** [comment]
No need on specific agent.name. I just wanted that field to exist to be consistent with all of the other integrations. Nothing vital, more nit picky.

**Comment by intxgo** [comment]
`agent.name` is defined as

>Custom name of the agent.

>
>This is a name that can be given to an agent. This can be helpful if for example two Filebeat instances are running on the same host but a human readable separation is needed on which Filebeat instance data is coming from.

>
>type: keyword

>
>example: foo

therefore it's arguably wrong that other integrations fill it on its own without any user consent.

**Comment by nicpenning** [comment]
This is interesting! I will take a look at the other dates sources. I had no idea that it is possible to set agent name.

**Comment by intxgo** [comment]
As you can see the issue is still open so you can't set the custom name yet, but it's possible to assign tags https://www.elastic.co/guide/en/fleet/current/filter-agent-list-by-tags.html

**Comment by nicpenning** [comment]
The only other Out of Box datasets that do not have agent.name are all of Elastic Defend is fleet_server.output_health.

So all other integrations from Elastic using Filebeat mainly all have agent.name. Just an observation I guess.
