### ISSUE TITLE
Access File

### ISSUE THREAD

**Issue by massimiliano-dalcero** [elastic/endpoint#8]
when enable "File" in fleet via endpoint "security integration" in the "event collection windows" we can monitor a lot of file event (deletion, modification, rename, ...) but NOT access/open file.

On windows system where agent is installed, we can see that elastic agent install a minifilter named "ElasticEndpoinDriver" , so we expects that "access file" can be monitored ... but nothing appen when a user access to a local file.

thanks and best regards

**Comment by gabriellandau** [comment]
Hi @massimiliano-dalcero.  Thanks for using Endpoint Security!

This is working as designed.  While technically possible given the filesystem minifilter as you described, Endpoint does not collect file accesses except in very limited circumstances.  This is done for performance purposes.  Reporting every file access on the system would generate far too much data, consuming too much CPU, bandwidth, and storage.

If you need to collect file open events, consider using Windows auditing with Winlogbeat.  Here is [a thread](https://discuss.elastic.co/t/winlogbeat-event-delete-folder-or-file/224401) talking about how to do that.

**Comment by massimiliano-dalcero** [comment]
Hi @gabriellandau ,
thanks for your kind answer :)
